### ISSUE TITLE
Create file when directory already exist

### ISSUE THREAD

**Issue by damienlagae** [Enabel/flysystem-sharepoint#8]
If the directory "/foo" already exist trying to add a file in "/foo/bar" doen't work
```php
$flysytem->write("/foo/bar/baz.txt", "content");
```
=> Call this method "->requestDirectoryMetadata("bar")". Because "/bar" doesn't exist on the root directory, it would then try to create "/foo/bar" and throw an exception because "/foo/bar" already exists.

**Comment by Miguel-Serejo** [comment]
Thanks for the quick fix!
